name: Base tests
on:
  pull_request:
  push:
    branches:
      - github-actions

permissions:
  contents: read

jobs:
  base-tests:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist
        working-directory: backend

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.4.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpm playwright install --with-deps

      - name: Run php server
        run: php artisan serve &
        working-directory: backend

      - name: Run base tests
        run: pnpm test:base
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKEND_URL: http://localhost:8000
          FRONTEND_URL: http://localhost:3000
